set(${PKG_SIMPLE_NAME}_INCLUDE_DIRS ${PKG_INSTALL_DIR}/include/luajit-2.0)
set(${PKG_SIMPLE_NAME}_LIBRARIES ${PKG_INSTALL_DIR}/lib/libluajit-5.1.a)

# Create project entry
ExternalProject_Add(${PKG_DISPLAY}
	DOWNLOAD_NAME ${PKG_DL_FILE}
	URL ${PKG_DL_URI}
	PREFIX ${PACKAGE_DIR}
	CONFIGURE_COMMAND ""
	BUILD_COMMAND make -j
	INSTALL_COMMAND make install PREFIX=${PACKAGE_DIR}/${PKG_DISPLAY}
	BUILD_IN_SOURCE 1
	BUILD_BYPRODUCTS
		${PKG_INSTALL_DIR}/libluajit-5.1.a
)
