set(${PKG_SIMPLE_NAME}_INCLUDE_DIRS ${PKG_SOURCE_DIR})

# Create project entry
ExternalProject_Add(${PKG_DISPLAY}
	DOWNLOAD_NAME ${PKG_DL_FILE}
	URL ${PKG_DL_URI}
	PREFIX ${PACKAGE_DIR}
	BUILD_COMMAND ""
	CONFIGURE_COMMAND ""
	INSTALL_COMMAND ""
	BUILD_IN_SOURCE 1
	BUILD_BYPRODUCTS ${PKG_SIMPLE_NAME}_LIBRARIES
)
