set(${PKG_SIMPLE_NAME}_INCLUDE_DIRS ${PKG_INSTALL_DIR}/include)
set(${PKG_SIMPLE_NAME}_LIBRARIES
	${PKG_INSTALL_DIR}/lib/libassimp.a
)

# Create project entry
ExternalProject_Add(${PKG_DISPLAY}
	DOWNLOAD_NAME ${PKG_DL_FILE}
	URL ${PKG_DL_URI}
	PREFIX ${PACKAGE_DIR}
	CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX=${PKG_INSTALL_DIR}
		-DBUILD_SHARED_LIBS=OFF
		-DASSIMP_NO_EXPORT=ON
		-DASSIMP_BUILD_ASSIMP_TOOLS=OFF
		-DASSIMP_BUILD_TESTS=OFF
		-DASSIMP_BUILD_NO_3DS_IMPORTER=ON
		-DASSIMP_BUILD_NO_AC_IMPORTER=ON
		-DASSIMP_BUILD_NO_ASE_IMPORTER=ON
		-DASSIMP_BUILD_NO_ASSBIN_IMPORTER=ON
		-DASSIMP_BUILD_NO_ASSXML_IMPORTER=ON
		-DASSIMP_BUILD_NO_B3D_IMPORTER=ON
		-DASSIMP_BUILD_NO_BVH_IMPORTER=ON
		-DASSIMP_BUILD_NO_COLLADA_IMPORTER=ON
		-DASSIMP_BUILD_NO_DXF_IMPORTER=ON
		-DASSIMP_BUILD_NO_CSM_IMPORTER=ON
		-DASSIMP_BUILD_NO_HMP_IMPORTER=ON
		-DASSIMP_BUILD_NO_IRRMESH_IMPORTER=ON
		-DASSIMP_BUILD_NO_IRR_IMPORTER=ON
		-DASSIMP_BUILD_NO_LWO_IMPORTER=ON
		-DASSIMP_BUILD_NO_LWS_IMPORTER=ON
		-DASSIMP_BUILD_NO_MD2_IMPORTER=ON
		-DASSIMP_BUILD_NO_MD3_IMPORTER=ON
		-DASSIMP_BUILD_NO_MD5_IMPORTER=ON
		-DASSIMP_BUILD_NO_MDC_IMPORTER=ON
		-DASSIMP_BUILD_NO_MDL_IMPORTER=ON
		-DASSIMP_BUILD_NO_NFF_IMPORTER=ON
		-DASSIMP_BUILD_NO_NDO_IMPORTER=ON
		-DASSIMP_BUILD_NO_OFF_IMPORTER=ON
		-DASSIMP_BUILD_NO_OBJ_IMPORTER=OFF
		-DASSIMP_BUILD_NO_OGRE_IMPORTER=ON
		-DASSIMP_BUILD_NO_OPENGEX_IMPORTER=ON
		-DASSIMP_BUILD_NO_PLY_IMPORTER=ON
		-DASSIMP_BUILD_NO_MS3D_IMPORTER=ON
		-DASSIMP_BUILD_NO_COB_IMPORTER=ON
		-DASSIMP_BUILD_NO_BLEND_IMPORTER=ON
		-DASSIMP_BUILD_NO_IFC_IMPORTER=ON
		-DASSIMP_BUILD_NO_XGL_IMPORTER=ON
		-DASSIMP_BUILD_NO_FBX_IMPORTER=ON
		-DASSIMP_BUILD_NO_Q3D_IMPORTER=ON
		-DASSIMP_BUILD_NO_Q3BSP_IMPORTER=ON
		-DASSIMP_BUILD_NO_RAW_IMPORTER=ON
		-DASSIMP_BUILD_NO_SIB_IMPORTER=ON
		-DASSIMP_BUILD_NO_SMD_IMPORTER=ON
		-DASSIMP_BUILD_NO_STL_IMPORTER=ON
		-DASSIMP_BUILD_NO_TERRAGEN_IMPORTER=ON
		-DASSIMP_BUILD_NO_3D_IMPORTER=ON
		-DASSIMP_BUILD_NO_X_IMPORTER=OFF
		-DASSIMP_BUILD_NO_GLTF_IMPORTER=ON
		-DASSIMP_BUILD_NO_3MF_IMPORTER=ON
	BUILD_BYPRODUCTS ${PKG_SIMPLE_NAME}_LIBRARIES
)
